motd: &3Welcome to &6Project Ares
motd2: &3Here you can play &bPvP minigames 24/7
motd3: &3Get started by &breading the book in your inventory
motd4: &3Read the rules by typing &b/rules
motd5: &3- - - - > &bHave fun!